-- =============================================================================
-- CORRECTIVE — restrict_fee_record_amount_paid_insert
-- Nom Cloud
--
-- Corrects 20260912000006_finance_rls (Phase 7 RLS batch 5).
-- No design number: per docs/SCHEMA_DESIGN.md standing rule 3, corrective
-- migrations carry no design number and name the migration they correct.
--
-- Found by Phase 8 batch 6 and recorded as §H.13 of
-- docs/PHASE8_CONNECTION_PLAN.md.
--
-- ---------------------------------------------------------------------------
-- WHAT WAS WRONG
-- ---------------------------------------------------------------------------
-- Migration 13 closed the amount_paid forgery it had measured, with:
--
--     revoke update on table public.fee_records from anon, authenticated;
--     grant update (school_id, student_id, term_id, category, amount,
--                   currency, due_date)
--       on table public.fee_records to authenticated;
--
-- That revoke names UPDATE and only UPDATE. The INSERT privilege was never
-- narrowed, so both anon and authenticated retained INSERT on all eleven
-- columns, amount_paid included. Measured state before this migration:
--
--   grantee         privilege  columns
--   --------------  ---------  -----------------------------------------------
--   anon            INSERT     id, school_id, student_id, term_id, category,
--                              amount, amount_paid, currency, due_date,
--                              created_at, updated_at
--   authenticated   INSERT     (the same eleven)
--   authenticated   UPDATE     school_id, student_id, term_id, category,
--                              amount, currency, due_date      <- correct
--
-- So the money guard held on one statement and not the other. Probed as an
-- administrator of their own school, with RLS enabled and all migration 13
-- policies in force:
--
--   update fee_records set amount_paid = 1000        DENIED 42501   (good)
--   insert into fee_records (..., amount_paid, ...)
--     values (..., 500, ...) on a fee of 500         OK             (the gap)
--   amount_paid on that row afterwards               500.00
--   fee_payments rows backing it                     0
--
-- An administrator could therefore create an invoice already marked settled,
-- with no payment behind it and no audit trail. It is the same forgery
-- migration 13 closed, one statement to the left.
--
-- It is narrower than the original. It applies only at creation, so a balance
-- already under way cannot be rewritten, and the running total of any fee that
-- has ever received a payment is still correct: the trigger recomputes the sum
-- over fee_payments and overwrites whatever was seeded. The exposure is an
-- invoice that is born a lie and never touched again.
--
-- ---------------------------------------------------------------------------
-- WHICH MECHANISM, AND WHY THIS ONE
-- ---------------------------------------------------------------------------
-- Two were available: a column-level INSERT grant, or a BEFORE INSERT trigger
-- forcing new.amount_paid = 0. A CHECK constraint is not an option at all,
-- because a CHECK cannot tell an INSERT from an UPDATE and the trigger must
-- remain free to write the column on UPDATE.
--
-- The column grant is used, because it was measured to close every route into
-- the column rather than only the obvious one. Probed with the grant in place:
--
--   named column list including amount_paid          DENIED 42501
--   no column list at all (positional, all columns)  DENIED 42501
--   insert ... select naming amount_paid             DENIED 42501
--   amount_paid given the DEFAULT keyword            DENIED 42501
--   upsert whose DO UPDATE sets amount_paid          DENIED 42501
--   legitimate insert omitting amount_paid           OK, column opens at 0.00
--   anon attempting any insert at all                DENIED 42501
--
-- The fourth line is worth keeping: privilege is checked on the named COLUMN,
-- not on the value expression, so even writing DEFAULT is refused. A client
-- must omit the key entirely, which is what PostgREST does when the payload has
-- no such field.
--
-- The trigger was rejected for two reasons. It would be a second, different
-- instrument guarding one column that already has one, so a future reader would
-- have to find both to understand the rule. And it would bind the table owner
-- too, which would block a privileged historical import of legacy fees that
-- carry real opening balances — a plausible need that the grant leaves open in
-- exactly the way migration 13's UPDATE restriction already leaves it open.
--
-- Parity with migration 13 is the point. Same instrument, same layer, same
-- roles, same column list philosophy. After this migration INSERT and UPDATE
-- finally say the same thing about amount_paid.
--
-- ---------------------------------------------------------------------------
-- WHAT THIS MIGRATION DOES NOT TOUCH
-- ---------------------------------------------------------------------------
-- No policy is created, altered or dropped. All twelve migration 13 policies on
-- fee_records and fee_payments are left exactly as they are, including the
-- guardian read path through is_guardian_of_fee_record.
--
-- sync_fee_record_amount_paid is not touched. It stays SECURITY DEFINER with
-- its pinned empty search_path, which is what lets it write amount_paid despite
-- the column restrictions. It performs UPDATEs only, never an INSERT, so
-- narrowing INSERT cannot reach it.
--
-- The three Phase 3 CHECK constraints are untouched: amount > 0,
-- amount_paid >= 0, amount_paid <= amount.
--
-- SELECT is untouched. amount_paid must stay readable — every fee screen shows
-- what has been paid, and the guardian read of their own child's balance
-- depends on it.
--
-- The column default of 0 is untouched and is now the only value a client can
-- start a fee at.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- The column-level INSERT grant, mirroring migration 13's UPDATE grant
-- -----------------------------------------------------------------------------
-- anon loses INSERT entirely and is granted nothing back, exactly as migration
-- 13 did for UPDATE. anon holds no INSERT policy on fee_records either, so this
-- is the grant ceiling agreeing with the policy layer rather than relying on it.

revoke insert on table public.fee_records from anon, authenticated;

-- `id` is included deliberately, though migration 13's UPDATE list omits it.
-- Repointing an existing row's primary key is meaningless, which is why UPDATE
-- excludes it; supplying one at creation is an ordinary client-generated-UUID
-- idempotency pattern, and the primary key is not a money column. Every other
-- column here is one the office legitimately fills in on a new invoice.
--
-- created_at and updated_at are excluded on purpose: they are server-maintained
-- and a client has no business setting either.

grant insert (id, school_id, student_id, term_id, category, amount, currency, due_date)
  on table public.fee_records to authenticated;


comment on column public.fee_records.amount_paid is
  'Running total of fee_payments against this record. Maintained ONLY by the sync_fee_record_amount_paid trigger, which is SECURITY DEFINER for that purpose. No client role can write it: migration 20260912000006 removed it from the UPDATE column grant, and this corrective removed it from the INSERT column grant. To change a balance, write a fee_payments row.';
