-- =============================================================================
-- Migration 03 (corrective) — drop_unapproved_contact_status_check
-- Nom Cloud · Phase 3 (production schema)
--
-- Removes contact_messages_status_check, a CHECK constraint that Migration 02
-- created but the approved design never specified.
--
-- WHY IT IS BEING REMOVED
-- Design §C table 4 defines contact_messages.status as:
--     status  text  NOT NULL  DEFAULT 'new'
-- and stops there. It names no value vocabulary. Migration 02 nevertheless added
--     CHECK (status IN ('new', 'handled'))
-- by INFERRING a vocabulary from the presence of handled_by and handled_at.
-- That inference was never approved, and an inferred constraint is not an
-- approved one. The schema must match the design, not a plausible reading of it.
--
-- The standing rule, as clarified: "status columns are text + CHECK, never
-- enums" means that WHERE the design defines a vocabulary, express it as a CHECK
-- rather than a Postgres enum. It does NOT mean every status column must carry a
-- CHECK. Where the design defines no vocabulary, the column stays plain text
-- with its default and no constraint.
--
-- WHAT status LOOKS LIKE AFTER THIS MIGRATION
-- contact_messages.status remains, intentionally and by approval:
--     text, NOT NULL, DEFAULT 'new'::text, with NO vocabulary constraint.
-- It stays unconstrained until a vocabulary is explicitly approved. Adding one
-- later is a single ALTER TABLE ... ADD CONSTRAINT — which is precisely why this
-- column is text rather than an enum.
--
-- SUPERSEDES MIGRATION 02's FOLLOW-UP NOTE 2
-- 20260903000002_platform_core.sql closes with a FOLLOW-UP block whose note 2
-- documents the CHECK and the reasoning behind its two values. That note is
-- OBSOLETE from this migration onward. It is left in place only because an
-- applied migration file is a historical record and must never be rewritten;
-- this header is the authority on the column's real state. Notes 1, 3 and 4 of
-- that block remain accurate and still stand.
--
-- No table, column, default, index, trigger or other constraint is affected.
-- Creates NO row-level security policies (Phase 7).
--
-- DROP CONSTRAINT is deliberately written WITHOUT "IF EXISTS": if the constraint
-- is already absent, the live schema is not what we believe it to be, and this
-- migration must fail loudly rather than pass in silence.
-- =============================================================================

alter table public.contact_messages
  drop constraint contact_messages_status_check;
